### PR TITLE
Try to detect if flash needs to be enabled (latched) separately

### PR DESCRIPTION
**Pull request by Flohack74**
Some devices need 2 commands to enable the torch, lets try to detect this and do the right steps.

### CODE REVIEW

**Review by fredldotme — APPROVED** [review]
Regression-tested on Xperia X, works well and doesn't look too complicated. LGTM

**Comment by jezek** [comment]
Device: FP2
Image: 2020-W35/2

Not working. ;)

**Comment by peat-psuwit** [comment]
@jezek please state if your FP2 is using an old or new (back) camera module. Currently, the flashlight does not work on a new camera module.

**Comment by Flohack74** [comment]
Tested OK with old camera module on devel 2020/09/15

**Comment by UniversalSuperBox** [comment]
Confirmed working on Xperia X, OnePlus One, Nexus 5. My FP2 has a burnt flash LED so I couldn't test it.

**Comment by jezek** [comment]
@peat-psuwit Using new camera module :( Does anybody know what's the problem with the new camera module and flashlight control?

**Comment by peat-psuwit** [comment]
It's simply that no one has written support for it. FP2's flashlight interface is different between the old and the new module, and some legwork needs to be done if we want to use it with the indicator.

**Comment by Flaburgan** [comment]
@jezek thanks to @peat-psuwit we're getting there as the new port for the Fairphone 2 based on Halium 7.1 + gstdroid allows me to take pictures with the flash working with the new camera module. So the torch shouldn't be far away.

**Pull request merged**
