### PR TITLE
add switch support

### PR DESCRIPTION
**Pull request by Vince1171**
and add more flashlight sysfs paths...
on the Oneplus3, in order to enable the torch, we need to do this:
```
echo 255 > /sys/class/leds/led\:torch_0/brightness 
echo 255 > /sys/class/leds/led\:switch/brightness
```
and to disable it:
```
echo 0 > /sys/class/leds/led\:torch_1/brightness 
echo 0 > /sys/class/leds/led\:switch/brightness
```
so this PR add the support

### CODE REVIEW

**Comment by Vince1171** [comment]
tested on Oneplus3 and Xiaomi mi5 for now

**Comment by Vince1171** [comment]
ping @mariogrip

**Review by mariogrip — APPROVED** [review]
LGTM :+1:

I'll hold this until next ota cycle, as we are in freeze :)

**Comment by halium-on-cedric** [comment]
looks good

**Comment by halium-on-cedric** [comment]
workes on cedric

**Comment by Vince1171** [comment]
@mariogrip as OTA-11 is out, can this PR be merged? :)

**Comment by UniversalSuperBox** [comment]
Do your devices all set brightness 255 when flipping the switch? I want to be careful, as sometimes we want to run the flash at a lower brightness to avoid burning it out. The "Flashlight" knob in Android will sometimes set a lower brightness than actual camera flash.

**Comment by Vince1171** [comment]
> Do your devices all set brightness 255 when flipping the switch? I want to be careful, as sometimes we want to run the flash at a lower brightness to avoid burning it out. The "Flashlight" knob in Android will sometimes set a lower brightness than actual camera flash.

the backlight brightness cannot be controlled
set brightness to 1 or 255 doesn't change anything (it's just != 0)
but yes, Android set it to 65 on op3t for example

**Comment by UniversalSuperBox** [comment]
@ubports-on-cedric, you say that this works for you as well. Does Android set a different brightness value on your device?

**Comment by Hacker1245** [comment]
@UniversalSuperBox cedric has the same brightness when flash is on as op3t (65)

**Review by UniversalSuperBox — APPROVED** [review]

**Review by UniversalSuperBox — CHANGES_REQUESTED** [review]
Wait, my testing methodology was flawed. This PR crashes the power indicator on the Oneplus One, when pressing the Flashlight switch. It exits with nothing more than a `Segmentation fault`.

Additionally, this introduces a warning into the build: https://ci.ubports.com/blue/organizations/jenkins/indicator-power/detail/PR-22/3/pipeline/24#step-38-log-1375

**Comment by Vince1171** [comment]
@UniversalSuperBox unfortunately I don't have a opo, so I cannot reproduce the segfault :/
For the warning, there is no line 1375 at the link you shared, only 1052...
Did you mean the ```warning: assignment discards 'const' qualifier from pointer target type``` at line 1459 and 1463 at https://ci.ubports.com/blue/rest/organizations/jenkins/pipelines/indicator-power/branches/PR-22/runs/3/nodes/24/steps/38/log/?start=0 ?

**Comment by tyg3rpro** [comment]
I tried the above commands on my note 4, I get an error saying it is not a file or directory, the contents of my /sys/class/leds is:

Red
Green
Blue
White
Display_Brightness
mmc0::
mmc1::

Not sure what the mmc stuff is, but Ill see if I can figure any of it out and report back

**Comment by wdehoog** [comment]
Please allow me a remark. I don't think it is a good idea to put code to support different devices in this indicator. Like brightness there needs to be an api to control the flash led. (Allthough I hope it can be implemented much more simple then in brightness.c). 

Maybe powerd is a good place to add the device support. Or all kernels need to provide the same led /sys/class entry.

**Comment by UniversalSuperBox** [comment]
I've filed https://github.com/ubports/indicator-power/issues/28 which tracks the fact that this is not an appropriate place to handle flashlight paths. However, since it functions correctly, I will merge #27 and recommend you add your paths to the file in the same way as is done there. Since this PR causes issues on other devices and appears to be deadlocked, I will close it for now. Please let me know if you think this is in error.

**Pull request closed without merging**
