### PR TITLE
Do not divide by battery size if percent less than 0.01

### PR DESCRIPTION
**Pull request by 0312birdzhang**
This pr is working on Xiaomi redmi 5 plus, Moto G5 and other devices(halium-7.). But, please validate it on some devices with more than one batteries, it should works.

### CODE REVIEW

**Comment by fredldotme** [comment]
LGTM, tested on MX4 and Xperia X.

**Comment by Vince1171** [comment]
same on Oneplus3(t)
ping @UniversalSuperBox

**Review by dobey — APPROVED** [review]

**Review by UniversalSuperBox — APPROVED** [review]
Seems okay on Qualcomm devices. I don't have any others to test and it's quite low-impact, so let's send it to devel.

**Comment by UniversalSuperBox** [comment]
@0312birdzhang, is there any specific way you would like to be credited in our changelog for our next release? Would you prefer your username...?

**Comment by 0312birdzhang** [comment]
@UniversalSuperBox username is OK :)

**Comment by UniversalSuperBox** [comment]
Great, thank you very much!

**Pull request merged**
